import { PureComponent } from 'react';
import { Icon } from 'antd';

const MyIconfont = Icon.createFromIconfontCN({
  // generated by iconfont.cn
  scriptUrl: 'https://at.alicdn.com/t/font_707688_7t32eukmyjt.js',
});

export default class MyIcon extends PureComponent {
  prefix = 'icon';

  render() {
    const { type, ...props } = this.props;
    return <MyIconfont type={`${this.prefix}-${type}`} {...props} />;
  }
}
